version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1.21.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn size
      - run: yarn test
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
workflows: 
  e2e_tests:
    jobs: 
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          no-workspace: true
          working_directory: ~/repo
          record: true
      