version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1.21.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node -v
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Install all node modules
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Code linting
          command: yarn lint
      - run: 
          name: Determin and check code size and load time
          command: yarn size
      - run: 
          name: Run unit tests
          command: yarn test
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
workflows:
  Build:
    jobs:
      - build
      - cypress/install:
          yarn: true
          build: yarn build
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          record: true
          requires:
           - cypress/install
      